import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, ChevronDown } from "lucide-react";
import { Link } from "react-router-dom";

const LimoAI = () => {
    const [openFaq, setOpenFaq] = useState(null);
    const [messages, setMessages] = useState([
        { sender: 'limo', text: 'Hi! I am LiMo AI Assistant. Ask me anything about crypto or the stock market.' }
    ]);
    const [inputValue, setInputValue] = useState("");
    const [isLoading, setIsLoading] = useState(false);
    const messagesEndRef = useRef(null);

    const isFirstMount = useRef(true);
    const scrollToBottom = (behavior = "smooth") => {
        messagesEndRef.current?.scrollIntoView({ behavior });
    };

    useEffect(() => {
        if (isFirstMount.current) {
            isFirstMount.current = false;
            return;
        }
        scrollToBottom();
    }, [messages, isLoading]);

    const handleSendMessage = async (e) => {
        if (e && e.key && e.key !== 'Enter') return;
        if (!inputValue.trim() || isLoading) return;

        const userMessage = inputValue.trim();
        setInputValue("");
        setMessages(prev => [...prev, { sender: 'user', text: userMessage }]);
        setIsLoading(true);

        try {
            const response = await fetch("https://n8n-32uz.onrender.com/webhook/market-research", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "Accept": "application/json"
                },
                body: JSON.stringify({ topic: userMessage })
            });

            let responseText = "";
            try {
                const contentType = response.headers.get("content-type");
                if (contentType && contentType.includes("application/json")) {
                    let data = await response.json();
                    // n8n often returns an array — normalize to the first item
                    if (Array.isArray(data)) data = data[0];
                    if (data && data.insights) responseText = data.insights;
                    else if (data && data.output) responseText = data.output;
                    else if (data && data.response) responseText = data.response;
                    else if (data && data.text) responseText = data.text;
                    else if (data && data.message) responseText = data.message;
                    else if (data && data.result) responseText = data.result;
                    else if (typeof data === 'string') responseText = data;
                    else responseText = JSON.stringify(data, null, 2);
                } else {
                    responseText = await response.text();
                }
            } catch (err) {
                responseText = await response.text() || "Received an empty response.";
            }

            setMessages(prev => [...prev, { sender: 'limo', text: responseText }]);
        } catch (error) {
            setMessages(prev => [...prev, { sender: 'limo', text: "Sorry, I couldn't reach the server right now.", error }]);
        } finally {
            setIsLoading(false);
        }
    };

    const faqs = [
        { q: "What is LiMo?", a: "LiMo is India's first AI-powered research assistant for stock market investing. It analyzes millions of data points to give you real-time insights." },
        { q: "Is LiMo's advice Ai registered?", a: "Yes, all trade ideas and research insights generated by LiMo are reviewed and approved by our Ai-registered research analysts." },
        { q: "How accurate is LiMo?", a: "LiMo leverages institutional-grade data and machine learning models to provide highly accurate portfolio audits and trade ideas." }
    ];

    return (
        <section className="py-14 sm:py-24 px-4 sm:px-6 bg-[#0B0D11]">
            <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-10 sm:gap-16 items-center">
                <div>
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-purple-500/20 bg-purple-500/5 text-purple-400 font-bold text-sm mb-6">
                        <Sparkles size={16} /> POWERED BY AI
                    </div>
                    <h2 className="text-3xl sm:text-4xl md:text-6xl font-black mb-6 sm:mb-8">Meet <span className="text-purple-500 font-black italic">LiMo</span></h2>
                    <p className="text-base sm:text-xl text-gray-400 mb-8 sm:mb-10 leading-relaxed">
                        Your personal AI research analyst. Get instant answers to your stock queries,
                        deep portfolio audits, and tailored trade ideas in seconds.
                    </p>

                    <div className="space-y-4 mb-10 sm:mb-20">
                        {faqs.map((faq, idx) => (
                            <div key={idx} className="border border-white/5 rounded-2xl overflow-hidden bg-white/5">
                                <button
                                    onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                                    className="w-full p-6 flex items-center justify-between text-left hover:bg-white/5 transition-colors"
                                >
                                    <span className="font-bold">{faq.q}</span>
                                    <ChevronDown className={`transition-transform duration-300 ${openFaq === idx ? 'rotate-180' : ''}`} />
                                </button>
                                <AnimatePresence>
                                    {openFaq === idx && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: "auto", opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            className="px-6 pb-6 text-gray-400 text-sm leading-relaxed"
                                        >
                                            {faq.a}
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </div>
                        ))}
                    </div>

                    <Link
                        to="/limo-ai"
                        className="inline-flex items-center gap-2 px-8 py-4 rounded-2xl bg-purple-500 hover:bg-purple-400 text-black font-bold text-base transition-all shadow-lg shadow-purple-500/20 mt-2"
                    >
                        <Sparkles size={18} />
                        Try LiMo AI — Free
                    </Link>
                </div>

                <div className="relative">
                    <div className="absolute inset-0 bg-purple-500/10 blur-[120px] rounded-full -z-10" />
                    {/* Chat Mockup */}
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        whileInView={{ opacity: 1, scale: 1 }}
                        className="bg-black/40 border border-white/10 rounded-[32px] sm:rounded-[48px] p-5 sm:p-8 backdrop-blur-xl shadow-2xl"
                    >
                        <div className="flex items-center gap-4 mb-10 border-b border-white/5 pb-6">
                            <div className="w-12 h-12 bg-purple-500 rounded-full flex items-center justify-center font-black italic text-black text-xl">
                                Li
                            </div>
                            <div>
                                <h4 className="font-bold">LiMo AI Assistant</h4>
                                <p className="text-xs text-green-500 flex items-center gap-1">● Online and analyzing</p>
                            </div>
                        </div>

                        <div className="space-y-6 max-h-[400px] overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent">
                            {messages.map((msg, idx) => (
                                <div key={idx} className={`flex gap-4 ${msg.sender === 'limo' ? 'flex-row-reverse' : ''}`}>
                                    <div className={`w-8 h-8 rounded-full flex-shrink-0 flex items-center justify-center ${msg.sender === 'limo' ? 'bg-purple-500 font-black italic text-black text-[10px]' : 'bg-gray-800'}`}>
                                        {msg.sender === 'limo' ? 'Li' : ''}
                                    </div>
                                    <div className={`${msg.sender === 'limo' ? 'bg-purple-500/10 rounded-tr-none border-purple-500/20' : 'bg-white/5 rounded-tl-none border-white/5'} p-4 rounded-2xl border max-w-[80%]`}>
                                        <p className="text-sm whitespace-pre-wrap">{msg.text}</p>
                                    </div>
                                </div>
                            ))}

                            {isLoading && (
                                <div className="flex gap-4 flex-row-reverse">
                                    <div className="w-8 h-8 rounded-full bg-purple-500 flex-shrink-0 flex items-center justify-center font-black italic text-black text-[10px]">Li</div>
                                    <div className="bg-purple-500/10 p-4 rounded-2xl rounded-tr-none border border-purple-500/20 max-w-[80%]">
                                        <p className="text-sm text-center italic mb-2">Analyzing...</p>
                                        <div className="flex gap-2 justify-center">
                                            <div className="w-1.5 h-1.5 bg-purple-500/60 rounded-full animate-pulse" />
                                            <div className="w-1.5 h-1.5 bg-purple-500/60 rounded-full animate-pulse delay-75" />
                                            <div className="w-1.5 h-1.5 bg-purple-500/60 rounded-full animate-pulse delay-150" />
                                        </div>
                                    </div>
                                </div>
                            )}
                            <div ref={messagesEndRef} />
                        </div>

                        <div className="mt-10 pt-6 border-t border-white/5">
                            <div className="bg-white/5 rounded-full px-4 py-2 flex items-center justify-between border border-white/5 focus-within:border-purple-500/50 transition-colors">
                                <input
                                    type="text"
                                    value={inputValue}
                                    onChange={(e) => setInputValue(e.target.value)}
                                    onKeyDown={handleSendMessage}
                                    placeholder="Ask anything..."
                                    className="bg-transparent border-none outline-none text-sm w-full px-2 py-2 placeholder:text-gray-500 focus:ring-0 text-white"
                                    disabled={isLoading}
                                />
                                <button
                                    onClick={(e) => { e.preventDefault(); handleSendMessage(); }}
                                    disabled={!inputValue.trim() || isLoading}
                                    className="p-2 rounded-full hover:bg-white/10 text-purple-400 disabled:opacity-50 disabled:hover:bg-transparent transition-colors flex-shrink-0"
                                >
                                    <Sparkles size={18} />
                                </button>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </div>
        </section>
    );
};

export default LimoAI;
